### ISSUE TITLE
Help panel icon needs to be updated

### ISSUE THREAD

**Issue by smaddox-sf** [forcedotcom/try-code-builder-feedback#114]
The help panel icon needs to be updated to the cloud+? icon as shown on the Welcome mat.  

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/59572234/161647620-a7afc71d-5e68-4826-9398-79f9eae26aee.png">

**Comment by jgellin-sf** [comment]
This is done. Will be reflected in next code builder image build.
