### ISSUE TITLE
Add Heroku CLI To Code Builder Workspaces

### ISSUE THREAD

**Issue by jjsfdc** [forcedotcom/try-code-builder-feedback#118]
End users cannot install Heroku CLI per their [INSTRUCTIONS](https://devcenter.heroku.com/articles/heroku-cli)

**Describe what you are ultimately trying to do**
Salesforce Functions has a "Heroku Data In Functions" feature, mentioned in [THIS BLOG](https://blog.heroku.com/data-in-functions) , that requires a user log into heroku and run a Heroku CLI command to associate the Functions Compute Environment with the Heroku data app.

**Describe how you think Code Builder can help solve your problem or improve your work**
All of the rest of the steps of Salesforce Functions development is possible with Code Builder. If the Heroku CLI were available within Code Builder, I wouldn't have to switch out of Code Builder to complete this task.

**Additional context**
The error I get when I try to install Heroku CLI is:

```
$ curl https://cli-assets.heroku.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1894  100  1894    0     0  72846      0 --:--:-- --:--:-- --:--:-- 72846
This script requires superuser access.
You will be prompted for your password by sudo.
sh: 10: sudo: not found
```

**Comment by smaddox-sf** [comment]
We don't plan to add this CLI at this time
