### ISSUE TITLE
Generate Project CLI Command Does Not Work

### ISSUE THREAD

**Issue by jjsfdc** [forcedotcom/try-code-builder-feedback#119]
**Describe the bug**
The CLI command `sf generate project` does not work in the Code Builder terminal.

**To Reproduce**
1. Open you Code Builder workspace
2. Close any open project via the "hamburger" UI
3. Open the terminal
4. Change to the /home/codebuilder directory by running `cd`
5. Type this command to create a new project: `sf generate project -n SomeProject` 

**Expected behavior**
A new Salesforce project is created in the /home/codebuilder/SomeProject directory

**Actual behavior**
The following is my output:
```
$ sf generate project -n SomeProject
 ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load 
 ›   /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@sf/gen/lib/commands/generate/project.js
 ›   Code: MODULE_NOT_FOUND
```

**Desktop (please complete the following information):**
 - OS: Mac OS 12.3.1
 - Browser: Google Chrome
 - Version 100.0.4896.75 (Official Build) (x86_64)

**Comment by smaddox-sf** [comment]
Code Builder is using sf v2 CLI.  Generate project isn't a current command.  ([cli command ref](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_generate_commands_unified.htm#cli_reference_generate_function_unified))
