### ISSUE TITLE
Authorize an Org doesn't redirect

### ISSUE THREAD

**Issue by randi274** [forcedotcom/try-code-builder-feedback#123]
**Describe the bug**
The command Authorize an Org usually opens a new tab/window to do just that. This just hung forever, and the command it gave me was confusing.

**To Reproduce**
1. Trigger 'SFDX: Authorize an Org' from the command palette
2. Click on it
3. Wait
4. See message in the terminal
5. Be confused

**Expected behavior**
Org browser should open a new tab, or maybe not be available? I'm actually not sure the use case for this command in code builder land

**Screenshots**
![Screen Shot 2022-04-05 at 4 53 15 PM](https://user-images.githubusercontent.com/9795193/161855951-006be6ad-84f6-4e88-bab0-812f292ec4ea.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome, latest

**Comment by jgellin-sf** [comment]
@smaddox-sf This work is scheduled for the next sprint and will be tracked henceforth with GUS story [W-11038644](https://gus.lightning.force.com/a07EE00000vYEIwYAO).
