### ISSUE TITLE
Make it harder to uninstall extensions?

### ISSUE THREAD

**Issue by randi274** [forcedotcom/try-code-builder-feedback#126]
**Is your feature request related to a problem? Please describe.**
It should be more difficult to uninstall the extensions. It's currently possible to get things into a really weird state, and I wasn't able to resolve it without deleting the environment. I hesitate to call this a bug, because it's really going off the rails to remove all of the extensions, but it might be good to prevent users from hosing their environment somehow. 

**Describe what you are ultimately trying to do**
If I get into a weird place having deleting an extension (or several), I'd like to be able to add them back more easily

Uninstalled all extensions 🚨

![Screen Shot 2022-04-05 at 5 40 31 PM](https://user-images.githubusercontent.com/9795193/161856840-078663b3-bc85-4e99-a628-ed6aa29003b1.png)

Could not add Code Builder or any extensions back, even on reload:
![Screen Shot 2022-04-05 at 5 41 33 PM](https://user-images.githubusercontent.com/9795193/161856911-f5ada564-fbcc-4180-b778-e8872aec8654.png)

**Comment by smaddox-sf** [comment]
You can still uninstall if you want to, but extensions will be back if you reload Code Builder.  Closing this as we won't take it further for now.  Based on customer feedback, we'll iterate further.
