### ISSUE TITLE
Got stuck after deleting environment - endless spinner on dashboard

### ISSUE THREAD

**Issue by randi274** [forcedotcom/try-code-builder-feedback#127]
**Describe the bug**
After hosing my environment in #126, I deleted it and refreshed the page. However, the old environment popped right back up as a cached environment, and I was unable to get a new environment. 

**To Reproduce**
1. Uninstall all extensions (maybe necessary?)
2. Delete environment since it's the only thing you can now do
3. Try to make a new one, go through flow again
4. See old org
5. See spinwheel of death continue forever

**Expected behavior**
Deleted env. should not be presented to the user again. A progress indicator, maybe. Also, don't take so long to make a new environment?

**Screenshots**

![Screen Shot 2022-04-05 at 5 43 43 PM](https://user-images.githubusercontent.com/9795193/161857404-f7c32995-39b6-4a4b-a526-45fc3fcb28a9.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome, latest

**Comment by smaddox-sf** [comment]
Fixed
