### ISSUE TITLE
Not sure about automatic save functionality

### ISSUE THREAD

**Issue by randi274** [forcedotcom/try-code-builder-feedback#130]
**General feedback**
In the desktop extensions, it's common to enable push on save and also detect conflicts on sync. However, when I did this, it was constantly throwing conflict errors since it was trying to deploy before I was ready. I'd like to be able to be able to choose whether or not to have save automatically enforced when I make fail changes, but also be able to use push on save.

**Comment by gbockus-sf** [comment]
@smaddox-sf The main difference I noticed when using code builder is it saves constantly, which is totally fine and better for a web based IDE. But this is different then the out of the box VSCode behaviour where it doesn't save until I execute a save for a particular file (or all files).  The only reason this matters is it will change the behavior of users slightly from what they are use to doing if they already use vscode. It might also be different from how the dev console work if I'm remembering correctly (doesn't save until I trigger a save).

**Comment by smaddox-sf** [comment]
@sbudhirajadoc - This is a good difference in behavior to add to the doc page

**Comment by smaddox-sf** [comment]
doc updated (or to be updated)
