### ISSUE TITLE
Cannot connect to the Extensions Marketplace

### ISSUE THREAD

**Issue by floralan** [forcedotcom/try-code-builder-feedback#131]
**Describe the bug**
When I search extensions in marketplace, whatever I typed into, it always shows this error: "We cannot connect to the Extension Marketplace at this time, please try again later."

**To Reproduce**
1. Go to 'Extension: Marketplace'
2. Search for any extension, for example: salesforce

**Expected behavior**
Show a list of extensions related to salesforce

**Screenshots**
<img width="535" alt="image" src="https://user-images.githubusercontent.com/42667832/161860963-30f11764-9ec9-4fd7-87bd-7c43fca1d1eb.png">

**Desktop (please complete the following information):**
- OS: iOS
- Browser: chrome
- Version: 11.6.5

**Comment by smaddox-sf** [comment]
documented known gap
