### ISSUE TITLE
A dead link on Code Builder Guide

### ISSUE THREAD

**Issue by floralan** [forcedotcom/try-code-builder-feedback#132]
**Describe the bug**
"See whats different in Code Builder" on Code Builder Guide is a dead link. 

**To Reproduce**
1. Go to 'Code Builder Guide'
2. Click on 'see whats different in Code Builder' at the right bottom of the page

**Expected behavior**
Should redirect to a web page. 

**Screenshots**
<img width="618" alt="Screen Shot 2022-04-05 at 3 33 27 PM" src="https://user-images.githubusercontent.com/42667832/161862007-6fee327a-933b-4e24-ba2f-7ab05423f370.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/42667832/161861611-ec268907-0b89-4dd6-9362-5ec28edfac27.png">

**Desktop (please complete the following information):**
- OS: iOS
- Browser: chrome
- Version: 11.6.5

**Comment by jgellin-sf** [comment]
This is the link we should use: https://developer.salesforce.com/tools/vscode

It works, but will not have relevant content until Beta is released.

**Comment by jgellin-sf** [comment]
GUS Ref: W-10981823
