### ISSUE TITLE
Update Extensions command results in error dialog

### ISSUE THREAD

**Issue by gbockus-sf** [forcedotcom/try-code-builder-feedback#135]
**Describe the bug**
If I run the update extensions command I get an error dialog 

**To Reproduce**
1. From the command pallet: Extensions: Check for Extension Updates
2. Enter
3. See error dialog below
![Screen Shot 2022-04-05 at 5 13 55 PM](https://user-images.githubusercontent.com/76090802/161866762-60aa5814-767a-45e4-a63e-76098810fde7.png)

**Expected behavior**
If CodeBuilder doesn't support updating extensions then probably a friendly error message.  Potentially make it where the command doesn't show up at all.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chome
 - Version latest

**Comment by smaddox-sf** [comment]
We will always keep the extensions up to date, so we won't address this at this time.
