### ISSUE TITLE
Code Builder should default to dark color theme like Visual Studio Code

### ISSUE THREAD

**Issue by thedanfernandez** [forcedotcom/try-code-builder-feedback#136]
**General feedback**

Code Builder should default to the same default color theme as Visual Studio Code, `Default Dark+` and  not light theme

**Comment by FabienTaillon** [comment]
Why not using dark/light depending on system setting ?

**Comment by JackVeromeev** [comment]
I suppose it is because the Salesforce UI (SLDS) doesn't yet support dark mode, so such light/dark change would not be confusing for newcomers
