### ISSUE TITLE
LWC Preview Component Locally doesn't work, and link to docs is broken

### ISSUE THREAD

**Issue by jeffb-sfdc** [forcedotcom/try-code-builder-feedback#139]
**Describe the bug**
Deploying a LWC component doesn't work "out of the box", and then the link to the doc to set up is broken.

**To Reproduce**
1. I created a LWC component
2. deployed
3. ran the SFDX: Preview Component Locally command
4. selected desktop

-> I got this:
Starting SFDX: Start Local Development Server

00:08:01.266 sfdx force:lightning:lwc:start
 ›   Warning: force:lightning:lwc:start is not a sfdx command.
Did you mean force:lightning:lwc:test:run? [y/n]: 
 ›   Error: Run sfdx help force for a list of available commands.
00:08:06.527 sfdx force:lightning:lwc:start
 ended with exit code 127

Error: To run this command, install the @salesforce/lwc-dev-server plugin. For more info, see [https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.get_started_local_dev](https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.get_started_local_dev).

5. I then went to https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.get_started_local_dev, but get the error, "Documentation for topic 'lwc.get_started_local_dev' does not exist for United States and version '54.0'."

**Expected behavior**
1. it would be nice if this command worked w/o any additional setup
2. the link should work

**Comment by smaddox-sf** [comment]
@sbudhirajadoc - A doc issue to look at: Within the description above, a broken doc link is mentioned.  (That is in the existing extensions vs. specific to Code Builder. )
