### ISSUE TITLE
Side help panel - remove options that aren't in SF context

### ISSUE THREAD

**Issue by smaddox-sf** [forcedotcom/try-code-builder-feedback#140]
(Screenshot below) The actions at the top of the side Help panel aren't in Salesforce context.  For example: ‘New File...’ opens a blank file.  We should be encouraging them to use `create` commands and start with a template.  [also - they could customize these templates for their team or organization!]

Let’s keep this panel focused on learning and applying Salesforce context.  For example - if they clone a repo that isn’t an sfdx project, none of the tooling activates.  how will they know that?  This will be confusing for novice users

Acceptance criteria:

* Remove these options from the box:
    * ‘New File...’, ‘Open....’, ‘Clone Git Repository...’
    * [we will eval and potentially add options post beta launch]
    * Leave the "Open Welcome page" option

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/59572234/162014899-2fd6f794-3e47-45db-b919-a62dceeee903.png">

**Comment by jonnyhork** [comment]
I created W-10977881 to cover this work

**Comment by jonnyhork** [comment]
https://github.com/forcedotcom/code-builder-vscode/pull/36
