### ISSUE TITLE
Not able to create a new LWC component.

### ISSUE THREAD

**Issue by VineethReddydazeworks** [forcedotcom/try-code-builder-feedback#146]
**Describe the bug**
A clear and concise description of the bug. What were you trying to do? What was your goal?
I was trying to create a new LWC using code builder. It gave the error as shown in screen shot while installing. I am using Developer Edition.
![Install Process Error](https://user-images.githubusercontent.com/49155883/178910269-fc4beeed-913a-49c6-b5c8-525fcd80b962.PNG)

**To Reproduce**
1. Go to Code Builder from App Launcher
2. After launching the code builder environment, i tried retrieving the existing LWC and Apex classes successfully.
3. I used 'ctrl+shift+p' command and searched for sfdx: create Lightning Web Component.
4. I have given the Label for the component, and selected the path. It gave me an error as shown in image in attachment and was unable to create new LWC. 

**Expected behavior**
Is should ideally create a new LWC component.

**Screenshots**
If applicable, add screenshots to help explain your problem.  They really help!

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : Version 103.0.5060.114 (Official Build) (32-bit)

**Smartphone or other device (please complete the following information):**

**Additional context**

I was trying to create new LWC component, but it gives me this error:
05:47:51.600 Starting SFDX: Create Lightning Web Component
cannot open vscode-remote://krill-d0rounf2q.builder.code.com/home/codebuilder/mysalesforceproject/force-app/main/default/lwc/DynamicDataTableLWC/DynamicDataTableLWC.js. Detail: Unable to read file 'vscode-remote://krill-d0rounf2q.builder.code.com/home/codebuilder/mysalesforceproject/force-app/main/default/lwc/DynamicDataTableLWC/DynamicDataTableLWC.js' (Error: Unable to resolve nonexistent file 'vscode-remote://krill-d0rounf2q.builder.code.com/home/codebuilder/mysalesforceproject/force-app/main/default/lwc/DynamicDataTableLWC/DynamicDataTableLWC.js')
![UnableToCreateNewLWC](https://user-images.githubusercontent.com/49155883/178909849-1a8f213d-064f-4227-977f-effe42268379.PNG)

**Comment by keirbowden** [comment]
I'm seeing the same error output, but the component is created in the lwc folder and and available for editing, pushing to the scratch org etc.

**Comment by smaddox-sf** [comment]
HI @VineethReddydazeworks - Please let us know if this is still an issue for you.  While we are late to respond here, we have not been able to reproduce this.
