### ISSUE TITLE
"Script-thrown exception" when clicking on "Join the Beta" in Code Builder Dashboard

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/try-code-builder-feedback#147]
**Describe the bug**
When going to Code Builder Dashboard and clicking on "Join the Beta", I'm seeing a "Script-thrown exception" error.
Also, documentation says that we should click on a "Get Started" button but I only have a "Join the Beta" one. I've installed the package via AppExchange listing, and it's v0.14 that gets installed.

**To Reproduce**
1. Go to Code Builder Dashboard
2. Click on "Join the Beta"

**Expected behavior**
I should be able to create a new Code Builder project.

**Screenshots**
<img width="1680" alt="cb1" src="https://user-images.githubusercontent.com/2465122/178943204-fba3ee6a-180d-4e91-82e4-8236b8cc689d.png">

<img width="1680" alt="cb2" src="https://user-images.githubusercontent.com/2465122/178943296-bbde352f-7bbc-422b-8262-95143bfd49c6.png">

**Desktop (please complete the following information):**
 - macOs
 - latest Chrome version

**Comment by jonnyhork** [comment]
@FabienTaillon Thanks for creating this issue in GitHub, we will look into this today!

**Comment by RupertBarrow** [comment]
I'm getting the same error.
Here is what I see in the Apex debug logs : 
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/48629751/179021694-64e7d53e-6bf4-470c-9309-09e4b70331b8.png">

**Comment by msrivastav13** [comment]
@jonnyhork Heads that I found if user don’t have English set in their locale it does not get you to the actual error and throws script exception!

**Comment by jonnyhork** [comment]
@FabienTaillon @RupertBarrow The issue appears to be related to the way we handle request validation from the managed package to our API. So far we are only seeing this with orgs based in Europe. It would be helpful for us get some information from you to debug the error.

If you are willing to share this information, can you please provide the values from these Apex methods?
```java
System.debug('User ID: ' + UserInfo.getUserId());
System.debug('User Name: ' + UserInfo.getUserName());
System.debug('Name: ' + UserInfo.getName());
System.debug('Org ID: ' + UserInfo.getOrganizationId());
System.debug('User Locale: ' + UserInfo.getLocale());
```
The easiest way will be to run this as "Anonymous Apex" in the Developer Console and then select "Debug Only" in the execution log. I am assuming you are familiar with this process, if not I would be happy to provide detailed instructions.

If you do not want to share the information in GitHub then you can email me at jhork@salesforce.com.

Thank you so much for the help, we really appreciate your time!

**Comment by Altanik** [comment]
Hello @jonnyhork,

Thank you for your responsiveness.

I'm having the same issue and I'm also based in Europe.

Please find below the output of the transmitted apex methods:

`10:58:32:006 USER_DEBUG [1]|DEBUG|User ID: 0057Q000005LC3VQAW`
`10:58:32:006 USER_DEBUG [2]|DEBUG|User Name: touimi.benj@gmail.com.codebuilder`
`10:58:32:006 USER_DEBUG [3]|DEBUG|Name: El Mehdi Touimi Benjelloun`
`10:58:32:007 USER_DEBUG [4]|DEBUG|Org ID: 00D7Q0000093bg3UAA`
`10:58:32:007 USER_DEBUG [5]|DEBUG|User Locale: fr_FR_EURO`

Regards

**Comment by jonnyhork** [comment]
We have identified the issue and pushed a new package version to all customers with `0.14` installed. You should now have `v0.15` installed in your orgs. 

Can you please try Code Builder again and let us know if you still have any issues, thanks!

**Comment by elliot41** [comment]
Hi @jonnyhork,

When clicking "Join the beta", I have the message "You will receive an email when your beta access has been granted."

Who will grant this access ? Is there a limit in the number of participants in the beta ? I still don't have received the email.

Thanks for your help,
Elliot

**Comment by jonnyhork** [comment]
@elliot41 Code Builder is in open beta and is available to try on a first-come, first-served basis. If no spots are available, you’re added to a waitlist, and receive an email when a spot opens up for you. We plan to increase the number of spots available every couple days, so you may get an email soon. Thanks for your patience!

**Comment by jonnyhork** [comment]
As far as we can tell this issue has been fixed with https://github.com/forcedotcom/workspace-manager-package/pull/209. If you are still having trouble using Code Builder, please let us know.
