### ISSUE TITLE
Error thrown when accessing Code Builder Dashboard when LWS is enabled

### ISSUE THREAD

**Issue by WSkrobekOrderfox** [forcedotcom/try-code-builder-feedback#148]
**Describe the bug**
When entering Code Builder Dashboard an error is thrown

**To Reproduce**
1. Install Code Builder managed package
2. Assign Permission Set
3. Go to Code Builder App

**Expected behavior**
Code Builder Dashboard is displayed

**Screenshots**
![Screenshot 2022-07-14 at 12 33 48](https://user-images.githubusercontent.com/92935530/178963177-f85212db-f86f-41ae-9342-572abe7aea23.png)

**Desktop (please complete the following information):**
 - OS: MacOd
 - Browser: newest Chrome (stable)

**Comment by cverhaest** [comment]
Same issue/bug on my side!
OS: MacOS Monterey
Browser: latest chrome version / same issue on firefox

**Comment by WSkrobekOrderfox** [comment]
Hi,
unfortunately it's sill the same issue

**Comment by cverhaest** [comment]
Hi,
It's stil the same issue on my side

**Comment by jonnyhork** [comment]
ok, sorry to hear that. We will look into it, thanks for letting me know!

**Comment by smaddox-sf** [comment]
Thanks for trying out Code Builder and for reporting this.  We are investigating this and it looks like it relates to other features enabled in an Org.  We will try to have a fix for this during beta, but we're still investigating at this point.  If you'd like to try out Code Builder, you could also use a Trailhead Playground orgs and [Developer Edition Orgs](https://developer.salesforce.com/signup).  I realize that might be less convenient.

**Comment by akruvi** [comment]
This is happening in my developer-edition org using 0.17. Is any specific functionality meant to be enabled in the org, maybe?

**Comment by jgellin-sf** [comment]
This happens in orgs where LWS is enabled. The only workaround at this time is to disable LWS. The Code Builder team is working towards an LWS-compliant solution.
