### ISSUE TITLE
Chatter required?

### ISSUE THREAD

**Issue by smaddox-sf** [forcedotcom/try-code-builder-feedback#151]
Two users have reported being blocked from installing the Code Builder beta package because Chatter is not enabled.  Screenshots of the review comments are below.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/59572234/179081635-eeb2bf44-afd2-4a08-9c70-ff40bb9fe2ce.png">

<img width="939" alt="image" src="https://user-images.githubusercontent.com/59572234/179081693-a98fe0ee-3102-4df4-8fbe-5caaca98e7cd.png">

**Comment by jonnyhork** [comment]
This issue was fixed in v.16.0
