### ISSUE TITLE
Time limit...really?

### ISSUE THREAD

**Issue by pledbetter-cvet** [forcedotcom/try-code-builder-feedback#154]
"20:00 Hours Remaining 

Expires on August 14, 2022"

Really? Come on guys..

**Comment by smaddox-sf** [comment]
During the open beta, usage per user is limited so that many people can check out Code Builder and give feedback.  Each user has 20 hours of usage over a month.  If there isn't a waitlist, you could grab another spot if there's more you want to check out.
