### ISSUE TITLE
While creating the environment it took more than 30 mins.

### ISSUE THREAD

**Issue by karkranikhil** [forcedotcom/try-code-builder-feedback#156]
**What is your role?**
Developer

**What do you normally work on when building on the Salesforce Platform?**
Everything

**What tools do you use today to develop on the Salesforce Platform?**
Visual studio code

**How do you see Code Builder fitting into your current workflow? Will it replace any tools you are currently using?**
Not much, but happy to explore.

**General feedback**
While creating the environment almost took more than 30 mins.

![image](https://user-images.githubusercontent.com/11937732/179329234-281ab9fa-35d3-4580-9746-e4fb75ae6e21.png)

**Comment by arun12209** [comment]
Same here. For me It took longer than an hour to create the environment.

**Comment by Abhishekrazy** [comment]
Yes, Same here, in VScode it's just a matter of seconds before the environment is created but it's taking so much more time. I think it's allocating the resources for us in our environment maybe that's the reason

**Comment by tellanad** [comment]
Same here , took more time .

**Comment by Insouciance** [comment]
Greater than 30 minutes and still going. To think I'll have to wait more than an hour is frustrating.

**Comment by smaddox-sf** [comment]
Thanks for reporting this.  We will investigate.  It should not be taking that long to create an environment.

**Comment by ryanbrainard** [comment]
This issue should now be resolved. We had a provisioning issue that we fixed on the backend. Please let us know if you continue to see issues. Sorry for the inconvenience this caused.
