### ISSUE TITLE
CodeBuilder.ResourceApiResponseException

### ISSUE THREAD

**Issue by arun12209** [forcedotcom/try-code-builder-feedback#159]
What is your role?
Developer

What do you normally work on when building on the Salesforce Platform?
Everything

What tools do you use today to develop on the Salesforce Platform?
Visual studio code

Bug/General feedback
It's been more than 24 hours and the environment is still not created.

![code_builder_error](https://user-images.githubusercontent.com/19918076/179386066-d7f73de9-cb1e-4e71-8b77-4c73f6f9fe42.png)

![code_builder_error1](https://user-images.githubusercontent.com/19918076/179386087-04c2cf14-d37a-485d-81b7-7351ee40b54f.png)

**Comment by jkranz-rk** [comment]
Also having this issue, haven't been able to successfully create an environment yet due to this
