### ISSUE TITLE
No Action taken place when Clicked on "Connect to Development Org"

### ISSUE THREAD

**Issue by Siddique-Ahmed06** [forcedotcom/try-code-builder-feedback#160]
Hello Team, 

Please look into this as Priority. 

App Launcher --> Code Builder --> Create Project --> Next -->  Connect to Developement Org -> No Action is performed

![image](https://user-images.githubusercontent.com/88406107/179400911-63d68a15-f589-464b-8af7-f781afb33823.png)

**Comment by Siddique-Ahmed06** [comment]
This is freaking Important to be fixed

**Comment by smaddox-sf** [comment]
Thank you for this feedback @Siddique-Ahmed06 .  We will investigate to see why the Connect isn't functioning for you.  We will post back if we have more questions as we try to repro it.

**Comment by Siddique-Ahmed06** [comment]
Hello @smaddox-sf  Please find the credentials for the above issue 
https://login.salesforce.com/?pw=Pikachu@123&un=siddique@ahmedsorganization.com

**Comment by keirbowden** [comment]
@Siddique-Ahmed06 - you might want to delete the comment above and DM instead - this is a public repo so anyone on the web can see how to get into your dev org.

**Comment by jfryman** [comment]
This looks to be the same issue as #162. Please follow that ticket for updates on this issue.
