### ISSUE TITLE
Waited more than hour. Environment creation ctill pending

### ISSUE THREAD

**Issue by Blackbackroom** [forcedotcom/try-code-builder-feedback#161]
Trying to setup environment to provide beta testing.
Waiting more then hour and environment creation still pending
<img width="326" alt="image" src="https://user-images.githubusercontent.com/40137179/179410878-e1a66af3-f95e-4d78-9b3f-b47c206597fc.png">

**Comment by Blackbackroom** [comment]
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/40137179/179411255-dd966272-c609-4fd9-a4ad-6d473d0b39ca.png">

**Comment by smaddox-sf** [comment]
Duplicate #156 .  We are investigating - please follow the other issue for updates.
