### ISSUE TITLE
Never get access to the Code Builder

### ISSUE THREAD

**Issue by fabioschiozer** [forcedotcom/try-code-builder-feedback#165]
**Describe the bug**
The following message appears after cliking Join
You will receive an email when your beta access has been granted. Changed your mind? Click below to cancel your request for beta access.

**To Reproduce**
1. Code Builder Installed in a Dev Org
2. Permission set Code Builder properly assigned
3. Goto do Code Builder app
4. Click join
5. Never get able to use it.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  They really help!

**Desktop (please complete the following information):**
 - OS: iOS Monterey
 - Browser Chrome
 - Version 103.0.5060.114 (Official Build) (x86_64)

**Comment by smaddox-sf** [comment]
Hi @fabioschiozer -  There is limited capacity during beta. The duration on the waitlist will vary depending on capacity and other users finishing their time with the Code Builder beta to open up a slot. You'll receive an email notification as soon as a spot opens up!
