### ISSUE TITLE
Need the "Salesforce XML Formatter" extension

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/try-code-builder-feedback#169]
**Is your feature request related to a problem? Please describe.**
SFDX does not always checkout XML contents in the same order, which leads to diffs and unnecessary merges.

**Describe what you are ultimately trying to do**
The "Salesforce XML Formatter" sorts the Salesforce XML metadata files at save time, which ensures that they will not cause unnecessary merges later.

**Describe how you think Code Builder can help solve your problem or improve your work**
We need to include the "Salesforce XML Formatter" extension.

**Additional context**

**Comment by smaddox-sf** [comment]
Thanks for trying out Code Builder and giving us feedback @RupertBarrow

**Comment by smaddox-sf** [comment]
From Code Builder, you can now [access any extension published to Open VSX](https://developer.salesforce.com/blogs/2023/06/open-vsx-extensions-are-now-supported-in-code-builder?utm_campaign=amer_sfld&utm_content=SalesforceDevs_&utm_medium=organic_social&utm_source=twitter).  It's up to individual publishers whether they add their extension to this public forum.
