### ISSUE TITLE
Currently i all setup basis of the salesforce document but i show this screen so how to solve it?

### ISSUE THREAD

**Issue by goc-kiran** [forcedotcom/try-code-builder-feedback#170]
![Lightning-Experience-Salesforce](https://user-images.githubusercontent.com/94962080/180214671-f92fca36-f4b4-4d33-b1d1-1be28ab1ad3e.png)

**Comment by smaddox-sf** [comment]
Hi @goc-kiran - You don't need to take any further action right now.  There is limited capacity during beta and this screen is telling you that you are on the waitlist. You'll receive an email notification when a spot opens up and then you can come back to this screen and create a Code Builder environment.  Thanks for your patience and eagerness to try out Code Builder!
