### ISSUE TITLE
Unable to install Code builder in our Sandbox

### ISSUE THREAD

**Issue by dinakarkuntalaSFDC** [forcedotcom/try-code-builder-feedback#171]
I can see the code builder app in app exchange but when I click on it - Nothing happens, Attaching the screenshot
<img width="493" alt="Codebuilder issue" src="https://user-images.githubusercontent.com/74759973/180726516-cf178d59-b2b3-4e27-b1fc-ddb201757b00.PNG">

**Comment by jgellin-sf** [comment]
@dinakarkuntalaSFDC Thanks for your interest in Code Builder. We are looking into why the in-app marketplace is not working. Please give installing directly from the [AppExchange listing](https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000HddeKUAR) a try.
