### ISSUE TITLE
Content is not allowed in prolog : While deploying the LWC

### ISSUE THREAD

**Issue by Prasanna29081979** [forcedotcom/try-code-builder-feedback#176]
**Describe the bug**
1. Refer your documentation page - https://developer.salesforce.com/tools/vscode/en/codebuilder/cb-start
2. In the section to "Create and Deploy a New Lightning Web Component", In newCBComponent.js-meta.xml, copy and paste the following code 
3. When we try to copy paste the code, it gives an error "Content is not allowed in prolog"...so unable and proceed further

**To Reproduce**
1. Go to 'Explorer, in new code builder, after connecting to an org'
2. Click on 'explorer then navigate to lwc after creating a new lwc component. Within that, navigate to <filename>.js-meta.xml'
3. copy paste the code given in your documentation "54.0 true lightning__AppPage lightning__RecordPage lightning__HomePage"
4. You 'll see the error as "Content is not allowed in prolog"
5.
**Expected behavior**
As per your documentation, it should allow me to save and subsequently deploy the new lwc

**Screenshots**
If applicable, add screenshots to help explain your problem.  They really help!
![image](https://user-images.githubusercontent.com/63204611/181446363-37e945cd-a03c-4ebc-b3f2-947b308ae1de.png)

**Google Chrome

**Comment by sbudhirajadoc** [comment]
Thanks for reporting this issue. The fix is in and should be live in the next release.
