### ISSUE TITLE
Remaining time still goes down after closing Code Builder tab

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/try-code-builder-feedback#178]
**Describe the bug**
When I finished using Code Builder, I closed my tab in Chrome, but could still see that the remaining time was going down in the Code Builder Dashboard. I tried to select "Sign out of code-server" but that didn't worked. I even tried to delete the env, and created a new one (I have to have one created to see the time remaining). Even without accessing the new one,  I can still see time decreasing.

**To Reproduce**
1. Open a Code Builder environment
2. Close the tab
3. Go back to Code Builder Dashboard
4. Notice the time remaining
5. Wait for 10mn
6. Refresh the page
7. Notice the time remaining

**Expected behavior**
As there is no active Code Builder environment, time remaining shouldn't decrease anymore.

**Screenshots**
<img width="1238" alt="CB1" src="https://user-images.githubusercontent.com/2465122/184108163-ec615171-4239-44c7-b1f9-cc990f71d57b.png">

<img width="1237" alt="CB2" src="https://user-images.githubusercontent.com/2465122/184108204-4facc6e8-3093-4afa-a584-2bcac6bd33ec.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Browser: Chrome 103.0.5060.134

**Comment by smaddox-sf** [comment]
Hi @FabienTaillon - Thanks for trying out Code Builder and giving us feedback.! Behind the scenes, we have some checks to try to detect when you are idle. When you close a tab or go idle, the session time should be within about 15-30 minutes of the rough time. Are you seeing the time tick down more than that?

We capped the hours per month for beta so that we could offer an open beta for anyone to try. Do you still have time remaining this month?

**Comment by FabienTaillon** [comment]
Hi @smaddox-sf,  got it, I don't think I tried to wait for 30mn as I deleted the env to be sure.
If it's working as expected then fine, just if once it's GA we still have a time limitation or need to pay to get more it would be frustrating to lose 30mn from time to time. 
Don't know if that would be possible to have a way to "disconnect" manually to be sure timing is stopped.

Anyway I still have some remaining time (it's back to 20h, don't know if you changed anything to reset my time ?).

**Comment by smaddox-sf** [comment]
Got it.  Thanks for the additional information @FabienTaillon .  I'm glad you have plenty of time to keep checking it out.  If you run out of time, hit me up :)

Thanks for the feedback about GA and how restricting by time might feel.  For beta, we went with _rough_ time limits as a simple way to make it open to all but have some limits for budget / abuse-prevention.
