### ISSUE TITLE
Opening CodeBuilder fails with CodeBuilder.TokenException error

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/try-code-builder-feedback#183]
*Describe the bug**
While trying to open Code Builder, it fails with a CodeBuilder.TokenException error.

**To Reproduce**
1. Go to CodeBuilder Dashboard
2. Click on "Launch"
 
I tried deleting and recreating an env with different setup (with a repo or without, connecting to a different devhub etc) but I'm getting the same error for every setup I tried.

**Expected behavior**
CodeBuilder is open.

**Screenshots**
<img width="661" alt="CodeBuilder" src="https://user-images.githubusercontent.com/2465122/186676261-59152f6c-f0dc-40e4-a345-bd05ac1fcc77.png">

**Desktop (please complete the following information):**
OS: macOS 12.5
Browser: Chrome 104.0.5112.101

**Comment by jgellin-sf** [comment]
Thanks for reporting @FabienTaillon. I rolled back some recent authentication changes. Please give it another try.

**Comment by jgellin-sf** [comment]
We discovered some back end issues due to an outage. Service is restored.
