### ISSUE TITLE
CodeBuilder stuck on "Code Builder is starting up..." page

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/try-code-builder-feedback#185]
**Describe the bug**
When opening CodeBuilder, the app is stuck on the "Code Builder is starting up..." forever.

**To Reproduce**
1. Go to CodeBuilder Dashboard
2. Click on Launch
3. Code Builder is stuck on "Code Builder is starting up..."  page

**Expected behavior**
CodeBuilder is opening.

**Screenshots**
<img width="1680" alt="cb" src="https://user-images.githubusercontent.com/2465122/187459938-d052ec57-4cee-4d93-b70b-8a360eccfdd8.png">

**Desktop (please complete the following information):**
 - macOS v12.5.1
 - Chrome v104.0.5112.101

**Additional context**
This is an env I've been using previously and was working, now isn't anymore.
Moreover, even though the page doesn't load, minutes are going down.
I haven't tried to delete/recreate yet as it's a little bit painful, as I'll have to setup everything again (connect to environments, connect to gitlab, clone everything etc)

**Comment by FabienTaillon** [comment]
Well eventually after several minutes (maybe 5 or 10), I ended up on the same error page as issue #183.
Now when I try to click on Launch from CodeBuilder Dashboard I'm getting this error immediately, not seeing the CodeBuilder loading page anymore.

<img width="1158" alt="cb2" src="https://user-images.githubusercontent.com/2465122/187461371-03e4b3b8-d921-4e9d-8946-c260551c6358.png">

**Comment by FabienTaillon** [comment]
I tried to delete and recreate the env but it doesn't work anymore, still seeing this issue.

**Comment by jonnyhork** [comment]
Thanks @FabienTaillon, the root of the error is the same as #183, we are working with our partners to resolve it now. I'll let you know when you should be good to go.

**Comment by jonnyhork** [comment]
@FabienTaillon Please try to access your environment again or create a new one, let me know if you still see this error. Thanks.

**Comment by FabienTaillon** [comment]
It's working now, thanks 👍
