### ISSUE TITLE
CodeBuilder disconnecting

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/try-code-builder-feedback#186]
**Describe the bug**
While working on CodeBuilder, I was suddenly disconnected, and CodeBuilder failed to reconnect. After 10mn trying to reconnect, I was able to launch it again from CodeBuilder Dashboard. However, I was in a state were I had some code neither deployed to the dev org nor committed to GitLab, which means I could have lost some work. Hopefully I was able to copy/paste my current opened tabs are paste them again when it worked again. But that's a little bit frightening to see we could lose some work if reconnection could not be done.

**To Reproduce**
Not really easy to reproduced, just happened while using CodeBuilder.

**Expected behavior**
CodeBuilder doesn't disconnect, or reconnect quickly.

**Screenshots**
<img width="516" alt="code builder" src="https://user-images.githubusercontent.com/2465122/187716883-77cd26d6-b55c-4c9c-82f9-c81993423f07.png">

<img width="1680" alt="error" src="https://user-images.githubusercontent.com/2465122/187716908-5c88811d-a524-4ea9-ac21-51f84145bbd4.png">

**Desktop (please complete the following information):**

- macOS v12.5.1
- Chrome v104.0.5112.101

**Comment by smaddox-sf** [comment]
Hi @FabienTaillon - Have you experienced this issue since?  We had a hiccup last week that might have caused this, but that was resolved, so I'm curious if you've continued to see it and if there might be something else going on.

**Comment by FabienTaillon** [comment]
I haven't worked a lot on CodeBuilder since then, but I haven't seen the issue again. If it's something you're already aware and have handled I guess this issue can be closed.

**Comment by FabienTaillon** [comment]
Got the same issue today, it wasn't able to reconnect, I had to start over and reopen it from the "launch" button from Salesforce UI.
I haven't used Code Builder for some time so don't know if it's still happening a lot or not, but it's still happening.

**Comment by smaddox-sf** [comment]
Thanks for reporting this @FabienTaillon .  When you were trying to reconnect to our Code Builder environment, were you going directly to a bookmarked URL for the Code Builder environment you had created previously?

**Comment by FabienTaillon** [comment]
It's mainly leaving the Code Builder tab to work in the org (like doing some CSS stuff directly in the browser), so maybe it becomes idle because of inactivity, but then never reconnects without me closing/reopening it.

<img width="537" alt="reconnect" src="https://user-images.githubusercontent.com/2465122/218055619-8d066b1d-ed45-46d2-bb91-733db35ee696.png">

**Comment by smaddox-sf** [comment]
Hi @FabienTaillon - We believe we have fixed this issue.  Please let me know if you are still experiencing problems.
