### ISSUE TITLE
Unable to create a scratch org with Code Builder

### ISSUE THREAD

**Issue by dustinrediess-sikich** [forcedotcom/try-code-builder-feedback#187]
Getting an error when trying to create a scratch org either with the cli or with the command palette in CB. Does appear there is a version update to the cli available but I can't update it in the environment either. 

**To Reproduce**
1. Launch code builder
2. Open terminal
3. Execute sfdx force:org:create command
OR
3. Use the 'create a default scratch org' command in the palette

![image](https://user-images.githubusercontent.com/104781417/188195257-0e18614c-6cf8-4cfe-91ee-280b7247ba0f.png)

Using `sfdx update` fails
![image](https://user-images.githubusercontent.com/104781417/188195504-84c2edb9-c73c-4664-93aa-ae18d84906b1.png)

Cannot update with NPM
![image](https://user-images.githubusercontent.com/104781417/188195654-0d08b41e-dc6a-4993-908e-8c3a69a7cb4c.png)

**Comment by jonnyhork** [comment]
Hi @dustinrediess-sikich can you please verify which type org you are authenticated to and have set as your default dev hub? As stated in #179 this may be an issue related to which org you are connected to? Thanks!

**Comment by dustinrediess-sikich** [comment]
I have CodeBuilder running on a scratch org and I believe it was connected to a DE org. My environment has since disappeared and I'm having new issues setting up a new one. Will try to set up CB on a DE org instead. 

![cb_env_error](https://user-images.githubusercontent.com/104781417/190006073-f3f6f86a-7e8c-43b5-84eb-81aeeeea6242.png)

**Comment by dustinrediess-sikich** [comment]
I've recreated on a Dev edition and it seems to be working as expected. It is possible the dev hub wasn't connected in the other org.

**Comment by smaddox-sf** [comment]
Hi @dustinrediess-sikich - Im glad you're unblocked.  Code Builder is meant to be installed in a more permanent org, so I think the org type is what caused the issue above
