### ISSUE TITLE
Unable to view full Activity Bar

### ISSUE THREAD

**Issue by EllieAtWHL** [forcedotcom/try-code-builder-feedback#188]
**Describe the bug**
Open Code Builder for the first time and read through Code Builder Guide. noted I could view what Org I am in by looking in the Activty Bar, but I cannot see the Activity Bar clearly. I have tried scrolling, changing window size and remove bookmark bar to create more space, but no matter what I do, I cannot view the full bar. Screenshpt attached showing just the top of the bar viewable.

**To Reproduce**
1. Open Code Builder

**Expected behavior**

Be able to view the Activity Bar properly to determine which Org I am in (amongst other things)

**Screenshots**
<img width="1920" alt="Screenshot 2022-09-13 at 11 18 09" src="https://user-images.githubusercontent.com/30699031/189877303-7af3f499-42d1-460d-88db-c8fa202aad05.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: Version 105.0.5195.102 (Official Build) (arm64)

**Comment by jonnyhork** [comment]
@EllieAtWHL Thanks for reporting an issue to us, we appreciate the feedback. However, I am unable to reproduce the behavior you are seeing with the same version of Chrome. I did a quick Google search and there may be an issue if "hardware acceleration" is enabled](https://support.google.com/chrome/thread/11539911/the-bottom-part-of-the-chrome-is-cut-off?hl=en). Can you check that setting in Chrome and see if turning it off fixes the issue for you?
Secondly, some people have reported certain Chrome themes can cause problems with rendering, could you try resetting back to the default theme at "chrome://settings/appearance"?

**Comment by EllieAtWHL** [comment]
@jonnyhork Thanks for investigating and responding so quickly. Neither of your suggestions worked unfortunately, however...
It did lead to me to realise it could be one of my Chrome extensions causing the issues, so I turned them all of and then turned them on one-by-one and was able to determine that is was one of them that caused the issues. For your information, in case this comes up again, the extension that caused the issue for me was RGBlind - an extension I use to detect potential issues in websites for people that are colour blind.

Thanks again for your help. This is no a bug with Code Builder itself so feel free to reject this.

**Comment by smaddox-sf** [comment]
Thank you for the further info @EllieAtWHL !  Super helpful in case anyone else hits this in the future.
