### ISSUE TITLE
Nothing happens after sandbox org is credentials are submitted

### ISSUE THREAD

**Issue by erodxd** [forcedotcom/try-code-builder-feedback#189]
Connect to Your Dev Environment[#](https://developer.salesforce.com/tools/vscode/en/codebuilder/cb-start/#connect-to-your-dev-environment)
From the App Launcher, find and open Code Builder.
Note: If you don’t see Code Builder as an option, or you see an empty screen when you launch it, contact your admin to make sure you have the correct license and permission set assigned to you.

Click Get Started.
Click New Project to create a new Salesforce DX project.
Give your project a name and choose Standard for project type.
**Next, connect an org to your Code Builder environment. You can choose to connect to a Salesforce org or a sandbox org.**

Nothing happens after this step. I just get brought back to this page:
![image](https://user-images.githubusercontent.com/42323101/190500482-58c22dfa-fe92-49b7-88c1-5a56a832a6ce.png)

**Comment by FenTro22** [comment]
I have the same issue.

**Comment by jonnyhork** [comment]
@erodxd @FenTro22 Thanks for reporting an issue, sorry you are having trouble creating a code builder environment. 

I will need some more details to investigate what might be happening.
1. What type of org are you installing Code Builder in? From the screenshot above it looks like a Sandbox?
1. Have you tried installing and creating an environment in a different type of org?
1. When you choose to connect to an org are you selecting a "Development Org" or a "Sandbox Org"?
1. Are you redirected to the Salesforce login to connect to an org or does the modal just close?
1. What operating system and browser are you using? What version of Code Builder is installed?

If you could provide an org id and user id that would be helpful. Any other screenshots or videos would also be helpful.

Thanks, I appreciate your time!

**Comment by FenTro22** [comment]
@jonnyhork 

I try to give you some more details.

1. Sandbox
2. no, just Sandbox
3. both
4. steps - GET STARTED --> New Project (enter Name and Project Type Standard) --> CONNECT a SANDBOX ORG --> redirect to Login in window from Salesforce to choose the user --> grant access --> and then I'm back to the dashboard site
5. Windows 10 - MS Edge

Please let me know if you need further information.

**Comment by FenTro22** [comment]
ideas?

**Comment by jonnyhork** [comment]
Hi @FenTro22, sorry for the delay here. I am unable to reproduce this issue using a Windows 10 machine and MS edge. I am able to successfully create an environment.

Have you tried using Code Builder with an org other than a Sandbox or a different browser on you machine?

**Comment by FenTro22** [comment]
Hi @jonnyhork, 
now I tried with chrome with the same result :-(
I tried with different sandboxes with the same result, I don't like connect the the live system.

Any other ideas?

**Comment by jonnyhork** [comment]
@FenTro22 I don't have any new ideas yet but would you be willing to create a login for me to one of your orgs where you see this issue and assign Codebuilder permissions to that user? Maybe I can get a better idea of whats happening. If that sounds ok then you can email me the credentials at jhork@salesforce.com
