### ISSUE TITLE
To Retrieve all component together

### ISSUE THREAD

**Issue by dekdas** [forcedotcom/try-code-builder-feedback#192]
As of now, in code builder we have to Retrieve each component separately. This increases the development time as we have to go to the org tab to retrieve the component and then come back to the explorer to open the class. It would have been better if we're able to retrieve all the component together so that we can do a "all file search".

**Comment by smaddox-sf** [comment]
Hi @dekdas  - I'm assuming you're using the Org Browser to retrieve the components?  There are a couple options that could help here:
 - When using Org Browser, you can retrieve all metadata of a certain type together (such as "Apex Classes").  You can do that by clicking the retrieve icon on the category level.  That will get you more metadata faster but not everything in one shot.
 - To retrieve all metadata, you can use a `package.xml` file.   [Here's a help page with some steps](https://help.salesforce.com/s/articleView?id=000381316&type=1) and [a page with sample code for `package.xml` files](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm), including retrieving all metadata.  

I'm curious if either of the above will work for you & your team?
