### ISSUE TITLE
Package xml download for backup

### ISSUE THREAD

**Issue by dekdas** [forcedotcom/try-code-builder-feedback#193]
I would love to have a feature through which I can retrieve the xml file of the whole or few components in the org to keep a backup of it.

**Comment by jfryman** [comment]
@smaddox-sf Would you think this is a feature for the extension that I can route over there, or should this stay with this side of the project?

**Comment by smaddox-sf** [comment]
You can control what you retrieve into your personal Code Builder environment via manifests.  ([Here's more about working with those](https://developer.salesforce.com/tools/vscode/en/user-guide/manifestbuilder).).
