### ISSUE TITLE
Apex Replay Debugger: Allow the Step Over function to be executed by one key only

### ISSUE THREAD

**Issue by caguirre2018** [forcedotcom/try-code-builder-feedback#194]
**Is your feature request related to a problem? Please describe.**
I was surprised to see that when doing a debug session on the apex replay debug in code builder, one has to type a combination of two keys to do a step-over. In VSCode you only have to type F10. It was annoying to have to type two keys to do a simple step over a line of code when debugging.

**Describe what you are ultimately trying to do**
I would like the process of stepping over lines of code to be easier

**Describe how you think Code Builder can help solve your problem or improve your work**
I think, if possible, code builder should allow only F10 to be used to do a step-over.

**Additional context**
In the screenshot below, you can see that I'm using a mac computer. In my case, in order to step over a line of code when debugging, I need to type Option + F10 to do that.
<img width="1716" alt="Step Over key" src="https://user-images.githubusercontent.com/7852586/192159449-ba07f22a-25ee-41d5-b75d-2800b693a4a5.png">

**Comment by smaddox-sf** [comment]
The hot key mapping for your browser can be slightly different than desktop.  You may be able to adjust the browser settings to tune the hotkeys in Code Builder
