### ISSUE TITLE
Connect multiple Orgs and metadata comparison feature would help a lot.

### ISSUE THREAD

**Issue by BAGiTO-Application** [forcedotcom/try-code-builder-feedback#197]
Since the Code Builder is native to Salesforce, its easy to access. It would be even better if we can connect to multiple orgs and do metadata comparison,

**Comment by smaddox-sf** [comment]
Hi @BAGiTO-Application - Thanks for trying out Code Builder and sharing feedback.  Within the Salesforce extensions (which can be accessed from Code Builder or VS Code), there is a Diff option.  This lets you compare your local project to an org.  For example, you could have one Org's metadata in your project within Code Builder (or VS Code) and then connect to the other Org you want to compare to.  You can right-click on the project folder and run the `SFDX: Diff Folder Against Org` to see all the differences. ([See doc about this command here](https://developer.salesforce.com/tools/vscode/en/user-guide/source-diff#site-main-content))

Have you tried out that command?
