### ISSUE TITLE
SOQL Builder Saves Blank Files when I Try To Export CSV Or JSON To My Local Computer

### ISSUE THREAD

**Issue by jjsfdc** [forcedotcom/try-code-builder-feedback#200]
**PROBLEM**
I would like to export CSV or JSON from SOQL Builder to my local computer.

**STEPS**
⇧⌘P, search "soql", and select "SFDX: Create Query in SOQL Builder"
create and run a simple query
in query results window, choose either "CSV" or "JSON" button
press the "Show Local" button in the dialog that appears
accept the filename suggested and save, noting the directory on your computer where it will save

**EXPECTED RESULT**
the saved file contains CSV or JSON data

**ACTUAL RESULT**
the file is empty

**Comment by 50471736** [comment]
Ditto.

**Comment by ryanbrainard** [comment]
Thank you for the bug report. I have been able to reproduce the issue and filed a bug report internally. As a workaround, you can first save the file in Code Builder and then right-click on the file to download it. Sorry for the inconvenience this is causing.

**Comment by floralan** [comment]
@jjsfdc This issue has been fixed and should be reflected in the latest version of SOQL Builder. I'm going to close this issue. Please let us know if you have more questions.

**Comment by floralan** [comment]
@jjsfdc We have merged the fix PR: https://github.com/forcedotcom/salesforcedx-vscode/pull/4754. 
You should see the fix in the next iteration. I'm closing this issue. Thank you so much for trying out Code Builder Beta.
