### ISSUE TITLE
SOQL Builder Saves to "/" Directory, Should Save To "Home" Directory

### ISSUE THREAD

**Issue by jjsfdc** [forcedotcom/try-code-builder-feedback#201]
PROBLEM
Every time I save a CSV or JSON file from SOQL Builder, I have to navigate from "/" to my "home" (/home/codebuilder) directory where all of my personal files are saved. I consider "/" to be a "system reserved" sort of location and "home" to be more appropriate for saving user-created files.

STEPS
⇧⌘P, search "soql", and select "SFDX: Create Query in SOQL Builder"
create and run a simple query
in query results window, choose either "CSV" or "JSON" button

EXPECTED RESULT
the dialog offers to save in my "home" directory

ACTUAL RESULT
the dialog offers to save in the "/" directory

**Comment by 50471736** [comment]
Yeah, I noticed that too.

**Comment by ryanbrainard** [comment]
Thank you for the bug report. I have been able to reproduced the issue and filed a bug report internally. Sorry for the inconvenience this is causing.

**Comment by floralan** [comment]
I'm closing this issue as we have the fix merged.

This should be reflected in the latest extension release.
