### ISSUE TITLE
1) Suddenly unable to launch project, msg "site can't be reached"; 2) The hours remaining in beta has gone up instead of down!

### ISSUE THREAD

**Issue by 50471736** [forcedotcom/try-code-builder-feedback#203]
These problems began a couple days ago.  I'm using Chrome. See attached images.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/16543260/198850961-7f6382c0-890a-4170-a06d-165d881650d5.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/16543260/198850991-9d2e06b5-f082-4346-a47e-ea842624e502.png">

**Comment by smaddox-sf** [comment]
Hi @50471736 - Thanks for trying out Code Builder and submitting this issue.  We believe the underlying cause of this has been solved.  Can you let us know if you are still experiencing an issue with seeing the "This site can't be reached" error?
