### ISSUE TITLE
Unable to launch today. Site not reachable

### ISSUE THREAD

**Issue by brij281** [forcedotcom/try-code-builder-feedback#204]
**Describe the bug**
A clear and concise description of the bug. What were you trying to do? What was your goal?

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  They really help!

**Desktop (please complete the following information):**

**Smartphone or other device (please complete the following information):**

**Additional context**

**Comment by code0100fun** [comment]
Thanks for reporting this issue. If you could add the instance URL to the description it would help us isolate the problem. Also, if you can still reproduce this issue and include a timestamp of when it happens that would help us as well.
