### ISSUE TITLE
Endless redirect loop when trying to launch Code Builder

### ISSUE THREAD

**Issue by christopher-camel-cognizant** [forcedotcom/try-code-builder-feedback#205]
**Describe the bug**
When attempting to launch the Code Builder, after clicking the 'Launch' button in the Code Builder Dashboard, the system gets stuck in an endless redirect loop; It endlessly redirects between the sandbox org URL and the Code Builder URL.

**To Reproduce**
1. Go to 'Code Builder Dashboard' in Developer Sandbox.
2. Click on 'Launch'.
4. See error.

**Expected behavior**
The Code Builder should load instead of endlessly redirecting.

**Screenshots**
![image](https://user-images.githubusercontent.com/65357317/200063152-553aeccf-e302-42b4-ace3-7da7b74c6151.png)
![image](https://user-images.githubusercontent.com/65357317/200063355-61b8a659-dc23-4cd3-bcb2-dffd855457db.png)
![image](https://user-images.githubusercontent.com/65357317/200063273-54f9303c-6f43-428c-b195-30671183d8aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chrome
 - Version 102.0.5005.63

**Comment by jonnyhork** [comment]
Hi @christopher-camel-cognizant, thanks for creating an issue here, it really helps us improve Code Builder. 

We are aware of the root cause in this case and it should be resolved now. Can you please try to access you environment again and let us know?
