### ISSUE TITLE
Add REST Client to Code Builder

### ISSUE THREAD

**Issue by jonnyhork** [forcedotcom/try-code-builder-feedback#206]
Creating a request to track it here.

This request is to add the REST Client VS Code extension to the pre-installed extensions in Code Builder

https://marketplace.visualstudio.com/items?itemName=humao.rest-client

Request in Slack form Jonathan Jenkins: https://salesforce-internal.slack.com/archives/C02JVA389BK/p1669762569893509

**Comment by smaddox-sf** [comment]
For GA, we're preloading the expanded extension pack for Salesforce.  We plan to stay in sync with that pack for the foreseeable future.  Any extension published to Open VSX is also possible to try on Code Builder after adding it to your personal Code Builder environment
