### ISSUE TITLE
Start without Git or Dev/Sandbox Org

### ISSUE THREAD

**Issue by rsindall** [forcedotcom/try-code-builder-feedback#207]
It would be great if it was possible to start without an existing github repo or org, and for the start up process two create them for you.

**Comment by smaddox-sf** [comment]
Hi @rsindall - Thanks for trying Code Builder and sharing feedback.  Can you tell me more about the use case you have in mind for this scenario?   Are you envisioning an empty org and empty repo?  Or would the org be a new scratch org or sandbox for development?  or something more like a Trailhead Playground org for learning?
