### ISSUE TITLE
Add Prequisites For Salesforce Functions in Python

### ISSUE THREAD

**Issue by jjsfdc** [forcedotcom/try-code-builder-feedback#208]
Per the [sf-functions-python](https://github.com/heroku/sf-functions-python) repo README instructions, the following base versions need to be installed in the development environment:

(requires python3 version 3.10 or higher)
```
$ python3 --version
Python 3.8.10
```
(requires git version 2.36.0 or higher)
```
$ git --version
git version 2.25.1
```

**Comment by smaddox-sf** [comment]
We don't plan to add this at this time
