### ISSUE TITLE
Code Builder Trial Time Elapsed

### ISSUE THREAD

**Issue by ejumich** [forcedotcom/try-code-builder-feedback#209]
**Describe the bug**
We only began using Code Builder this month, and have only had about 10~ hours of active use. On 1/9, we had 4.5 hours left with the tool completely closed, and nobody in the environment. Today we have 0 hours left in our trial. 

**To Reproduce**
1. Navigate to Code Builder and start the environment
2. Close the window in your browser
3. Time elapsed continues to decrease for hours after the initial window was closed. 

**Expected behavior**
We would expect only a small amount of time to elapse after the window was closed, but hours were removed from our limit. 

**Screenshots**
![Screenshot 2023-01-10 142011](https://user-images.githubusercontent.com/122398226/211642197-22b59056-5e7a-4c47-b5ec-f524a7d8e435.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, 
 - Browser Chrome Version 108.0.5359.125 (Official Build) (64-bit)

**Smartphone or other device (please complete the following information):**
 - Device: Samsung Tab S8+
 - OS: Android 13
 - Browser Chrome
 - Version 108.0.5359.128
**Additional context**

Organization ID: 00D6u0000000MSV
Code Builder has been fantastic , we really have enjoyed using the tool. It has made building a LWC significantly easier. I have used it with both an Android Tablet and Windows PC with great results in both cases.

**Comment by floralan** [comment]
@ejumich Thank you for using our service. Could you please give me the Codebuilder instance URL so that I can investigate it further?

**Comment by floralan** [comment]
We have identified an issue that makes an instance run longer than it should and we've added it to our work tracker.

**Comment by smaddox-sf** [comment]
Hi @ejumich - We believe we have fixed this issue.  Please let us know if you still see any problems.
