### ISSUE TITLE
Issues with SFDX CLI not up to date

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/try-code-builder-feedback#211]
I'm using local VS Code on a computer, and get a warning that flags need to be replaced in one command:

<img width="917" alt="VS Code" src="https://user-images.githubusercontent.com/2465122/218100961-dd0a0941-72da-4b74-abc0-4a194aa2f0a8.png">

I change them in my scripts, push to GitHub.
Later on, on another computer where I don't have everything installed I use Code Builder, but then the updated script doesn't work:

<img width="903" alt="Code Builder" src="https://user-images.githubusercontent.com/2465122/218101054-3d312427-baab-4e9b-a230-f7724091e2cf.png">

This Code Builder env has been created this week, so it's not an old one, but still it has an old CLI version, 2 months according to the CLI release date:
https://www.npmjs.com/package/sfdx-cli?activeTab=versions

So there are 2 problems to me:
- Code Builder should be up to date with the CLI version when we create a new one
- Not being able to `sfdx update` prevent us from solving this

**Comment by jonnyhork** [comment]
@FabienTaillon Thanks for creating this issue. We recently updated the image behind Code Builder, which includes the latest version of the CLI at the time of its release. If you start any of your Code Builder instances and check the CLI version with `sfdx --version` we should expect to see `sfdx-cli/7.188.1 linux-x64 node-v18.12.0`. Please let me know you still see an older version.

**Comment by FabienTaillon** [comment]
Thanks. I think the [SalesforceDX docker image](https://hub.docker.com/r/salesforce/salesforcedx) is updated every week like the CLI, could be good at some point to have the same release update for CodeBuilder image.
I'll use the npm way to update in the meantime, thanks 👍

**Comment by jonnyhork** [comment]
Sounds good, we definitely have plans to improve how we manage the Code Builder image so that there are regular, mostly automated updates similar to the SFDX docker image. Thanks for your patience on this.

Ironically, since I told you we updated the Code Builder image yesterday, we discovered a regression and had to roll back to an earlier version. We are working on a fix, but I think you should be ok with npm for now.
