### ISSUE TITLE
Reverse Roll back  or sync feature request

### ISSUE THREAD

**Issue by Giloy1903** [forcedotcom/try-code-builder-feedback#214]
**Is your feature request related to a problem? Please describe.**
Many times, I face issue where we are unable to perform reverse rollback. Is there any time line for this feature

**Describe what you are ultimately trying to do**
During production deployment, due to buggy code in place, many times we have to roll back and that too selectively. For ex, out of five stories, we want to roll back 2 stories that has caused some blocker issues in Prod so we should have a UI/UX friendly screen to achieve this 

**Describe how you think Code Builder can help solve your problem or improve your work**
During production deployment, due to buggy code in place, many times we have to roll back and that too selectively. For ex, out of five stories, we want to roll back 2 stories that has caused some blocker issues in Prod so we should have a UI/UX friendly screen to achieve this 

**Additional context**
During production deployment, due to buggy code in place, many times we have to roll back and that too selectively. For ex, out of five stories, we want to roll back 2 stories that has caused some blocker issues in Prod so we should have a UI/UX friendly screen to achieve this

**Comment by smaddox-sf** [comment]
Hi @Giloy1903 - Thanks for trying out Code Builder and sharing feedback.  Can you elaborate more on your release process?

What tools are you using for the original deployment?

What manual steps or tools do you use today when you have to perform a rollback?
