### ISSUE TITLE
Code Builder takes time to load and kept users wait indefinitely. 

### ISSUE THREAD

**Issue by Giloy1903** [forcedotcom/try-code-builder-feedback#215]
**Describe the bug**
Post org authorization, when we get a name of the project, trying to ‘Launch’ redirects user to a new tab showing “ Code Builder is starting up....” Message for several minutes. There is no progress bar or banner message letting user to wait indefinitely. In my case, I connected one demo project and had to relaunch the screen to get the Code Builder IDE. I wish we can see this issue

**To Reproduce**
Post org authorization, when we get a name of the project, trying to ‘Launch’ redirects user to a new tab showing “ Code Builder is starting up....” Message for several minutes. There is no progress bar or banner message letting user to wait indefinitely. In my case, I connected one demo project and had to relaunch the screen to get the Code Builder IDE. I wish we can see this issue

**Expected behavior**
Code builder should not wait that long during Launch or have some UX friendly Banner or progress bar to let developer( user) know what's going on or how much time they have to wait.
**Screenshots**
I am unable to locate the attachment where I can share the images. Post org authorization, when we get a name of the project, trying to ‘Launch’ redirects user to a new tab showing “ Code Builder is starting up....” Message for several minutes. There is no progress bar or banner message letting user to wait indefinitely. In my case, I connected one demo project and had to relaunch the screen to get the Code Builder IDE. I wish we can see this issue

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Mac OS 13.2.19Ventura)
 - Browser [e.g. chrome, safari] Chrome(Version 110.0.5481.177 (Official Build) (arm64))

**Smartphone or other device (please complete the following information):**
NA
**Additional context**
NA

**Comment by jfryman** [comment]
Hi @Giloy1903. Thanks for the report. If I may better understand - were you able to get into Code Builder IDE after you reloaded, or was it that you were not able to get into the web IDE at all?

**Comment by floralan** [comment]
@Giloy1903 Hi, we have fixed this issue, so I'm closing it here. Please let us know if you are still experiencing the same problem.
