### ISSUE TITLE
Getting CodeBuilder.TokenException error

### ISSUE THREAD

**Issue by msbagul** [forcedotcom/try-code-builder-feedback#218]
**Describe the bug**
I have installed Code Builder(Beta) in my developer org. Installation went successful. I have assigned Permission Set and then attempted to start using code builder. When I click "Launch" button on the code builder dashboard, I am getting error as shown below.
--------------------------------------------------------------------------------------------------------------------------------------------
CodeBuilder.TokenException

We can't retrieve the access token. Try again. If you still encounter errors, contact Support and provide the error details.

 {
  "statusCode": 500,
  "name": "CodeBuilder.ResourceApiResponseException",
  "exceptionLabel": "There was an error communicating with the workspace. Try again later. If you still encounter errors, contact Support and provide the error details.",
  "details": "Internal server error"
}
--------------------------------------------------------------------------------------------------------------------------------------------

**To Reproduce**
1. Launch "Code Builder(Beta) from application launcher menu".
2. Click Launch button.
3. My dev org id is 00D5e0000014X61

**Expected behavior**
Code builder should have been launched.

**Screenshots**
![image](https://user-images.githubusercontent.com/14172815/223709510-711a64a4-b1b7-4bfa-b191-cb42d19adfe0.png)

**Desktop (please complete the following information):**

**Smartphone or other device (please complete the following information):**

**Additional context**

**Comment by jgellin-sf** [comment]
@msbagul Thanks for your interest in Code Builder. I am an engineer on the team. We are investigating this problem and will update this issue when it is fixed.

**Comment by jgellin-sf** [comment]
Our service experienced an outage in certain regions. We have fixed the problem and service is restored in all regions.
