### ISSUE TITLE
Code Builder Extensions

### ISSUE THREAD

**Issue by smnryn999** [forcedotcom/try-code-builder-feedback#219]
**Describe the bug**
When we created a project in code builder before, Salesforce extensions were coming pre-installed. Now there is no Salesforce Extension Pack and we cannot install it ourselves, too.

**Expected behavior**
I want Salesforce Extension Pack to be installed as past, so that we can create and deploy components.

**Screenshots**
![Screenshot_20230313-145956_Opera](https://user-images.githubusercontent.com/96185425/225011733-8d693f1b-3f1a-4cb7-85f3-bb7a64e9ffb7.jpg)

**Smartphone or other device (please complete the following information):**
 - Device: Samsung Tab A7
 - Browser: Opera, Firefox, Chrome

**Comment by aaronromeo** [comment]
Hi @smnryn999 we are troubleshooting the issue. In the interim, can you please recreate your environment? It should spin up with all the appropriate extensions installed.

**Comment by smnryn999** [comment]
Hi @aaronromeo, the issue has been fixed. Thanks for your help.
