### ISSUE TITLE
Hours Remaining keep decreasing after closing the code builder tab

### ISSUE THREAD

**Issue by craigd-sua** [forcedotcom/try-code-builder-feedback#222]
**Describe the bug**
After closing the folder in code builder and closing the tab, the hours remaining displayed on the Code Builder Dashboard within Salesforce keep ticking down.

**To Reproduce**
1. Launch Code Builder
2. File / Open Folder
3. File / Close Folder
4. Close Code Builder Tab

**Expected behavior**
Hours remaining would stop decreasing

**Screenshots**
Hours remaining after closing the Code Builder Tab
![image](https://user-images.githubusercontent.com/109558700/229003663-4208077b-d049-4f17-8ca2-90838a6157bb.png)

Hours remaining a few minutes later
![image](https://user-images.githubusercontent.com/109558700/229003900-86a1f6e0-21b0-4101-8850-75a958e14257.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 111.0.5563.147 (Official Build) (64-bit)

**Smartphone or other device (please complete the following information):**

**Additional context**
I also tried logging out of Salesforce to see if that would stop the hours remaining decreasing, but it didn't.

**Comment by craigd-sua** [comment]
An hour later, the hours remaining is still decreasing
![image](https://user-images.githubusercontent.com/109558700/229015166-f4137382-c202-4bea-9c7a-19d165c87a3c.png)

**Comment by smaddox-sf** [comment]
Hi @craigd-sua - Thanks for reporting this.  When you close your tab, it can take up to 15 minutes for things to timeout and a session to end.  Because of this, it's normal to see some discrepancy as the count is not exact to the minutes.  However, it looks like you saw more than hour run off after you closed the browser tab.  We'll investigate this.

Did the clock eventually stop?

**Comment by craigd-sua** [comment]
It did stop at 18:34
![image](https://user-images.githubusercontent.com/109558700/229649796-4eb3c496-f80d-401d-87ab-119d17f69499.png)

**Comment by smaddox-sf** [comment]
Hi @craigd-sua - We believe we have fixed this issue.  Please let us know if you're still seeing problems.
