### ISSUE TITLE
See a message complaining that the Salesforce Extension isn't found in the marketplace

### ISSUE THREAD

**Issue by Rezhilprakash** [forcedotcom/try-code-builder-feedback#224]
The 1 extension(s) below, in workspace recommendations have issues: salesforce.salesforcedx-vscode (not found in marketplace)

**Comment by smaddox-sf** [comment]
Hi @Rezhilprakash - Thanks for trying out Code Builder and sharing feedback.  You can safely ignore that message.  It is there for now until we get the Salesforce Extensions published on the marketplace, which is in process. The Salesforce Extensions are still loaded and should be working for you.  Let us know if that's not the case.

**Comment by floralan** [comment]
@Rezhilprakash We have published extensions on the marketplace. You should not see the warning message anymore. I'm closing this issue. Please let us know if you have more questions. Thank you for your feedback!
