### ISSUE TITLE
Time remaining not working properly - some users cannot launch Code Builder

### ISSUE THREAD

**Issue by Nat-guillon** [forcedotcom/try-code-builder-feedback#225]
I installed it in my playground, try to launch it in June, but after few attempts I got the "No time remaining" notification...Humm ? OK.... Maybe I forgot to close my browser yesterday evening... Retried today, FOR THE FIRST TIME IN JULY, click on the launch button, saw the bear "loading etc", after 5 mins, refreshed my page to see if something could change, and receive the "No time remaining"... Seriously ?

**Comment by jfryman** [comment]
@Nat-guillon I'm sorry you're having issues. Would you be able to share your OrgID and UserID for us to take a look into this? 

Thanks!

**Comment by smaddox-sf** [comment]
Duplicate of #226
