### ISSUE TITLE
Code Builder Time Reset Bug

### ISSUE THREAD

**Issue by Sharath511** [forcedotcom/try-code-builder-feedback#226]
When we launch the code builder and close the tab in which code builder is present, the time i.e., 20 hours will be reset and we cannot launch the code builder again. Please consider the issue and and resolve as soon as possible as we are not able to work efficiently.

**Comment by hcarnes** [comment]
@Sharath511 Thanks again for reporting this issue. We fixed the problem with the timeout and you should be able to launch Code Builder again without any issues. Please let us know if you encounter any other problems or have any feedback. Have a great day! 😊

**Comment by GH4Arlene** [comment]
Thank you so much, and thank you again for a great tool.  I will be preferring it over my desktop VSCode whenever possible.
