### ISSUE TITLE
Love It (Minus the time reset bug already reported)

### ISSUE THREAD

**Issue by GH4Arlene** [forcedotcom/try-code-builder-feedback#227]
**What is your role?**  Developer

**What do you normally work on when building on the Salesforce Platform?**  Apex, LWC, Visualforce

**What tools do you use today to develop on the Salesforce Platform?**  VSCode

**How do you see Code Builder fitting into your current workflow? Will it replace any tools you are currently using?**  I expect to continue to use VSCode for work in the short term, but CodeBuilder for volunteer work as soon as it is GA.  The next time I need get a new work laptop, I may not install VSCode on the laptop.  Maintaining that environment is time-consuming.  (caveat: this is based on using it for only 2 hours).

**General feedback**  I love it!!  So much faster than working locally.  Everything was just the same as in VSCode on my laptop.  There was nothing to learn.  I just started developing! Was really disappointed when I only got to use it for 2 hours, but it thought I'd already used up my time for the month.  That bug has already been reported, and a work item set for it, so am looking forward to it getting fixed.  May have more feedback for you at that time.  Great job, and thank you!

**Comment by hcarnes** [comment]
Thank you for the feedback! To help you get back to coding, please send us your orgId and userId. We’re also fixing the issue that resets your time limit. We appreciate your patience and understanding!

**Comment by hcarnes** [comment]
@GH4Arlene We fixed the problem with the timeout and you should be able to launch Code Builder again without any issues. Please let us know if you encounter any other problems or have any feedback. Have a great day! 😊
