### ISSUE TITLE
code builder dashboard problem

### ISSUE THREAD

**Issue by gagangupta05** [forcedotcom/try-code-builder-feedback#229]
### Summary

when I am install the code builder package and assign the permission correctly but getting error on  UI when open code builder in app launcher 

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

getting the perfect screen dashboard UI of code builder 

### Actual result

getting error on the ui

### Additional information

![codebuilder](https://github.com/forcedotcom/salesforcedx-vscode/assets/106859888/f485b2e6-fbbb-4cc7-98de-275c331378d9)

**Salesforce Extension Version in VS Code**:

**SFDX CLI Version**:

**OS and version**:

**VS Code version**:

**Comment by smaddox-sf** [comment]
Hi @gagangupta05 - Unfortunately, Open Beta ended last week and this package is no longer available publicly.  We're in the middle of preparing for GA launch later this month. Once we launch GA you will be able to create a new environment. 
 Please stay tuned in the coming weeks for our GA announcement as well as details on how to setup Code Builder once it's released.
